version: '3.9'
services:
  backend:
    build: ../..
    command: uvicorn backend.app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - ../..:/app
    environment:
      - DATABASE_URL=
  frontend:
    image: node:18
    working_dir: /app/frontend
    command: npm run dev
    volumes:
      - ../..:/app
    ports:
      - "3000:3000"
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
